public with sharing class VSclasses2 {
    public VSclasses2() {
        /*new comment will be pull be VS code*/

        /*
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<types>
		<members>Account</members>
		<name>CustomObject</name>
	</types>
	
	<types>
		<members>*</members>
		<name>Workflow</name>
	</types>
	<version>51.0</version>
</Package>*/
            }
}