public with sharing class VSclasses2 {
    public VSclasses2() {
        /*new comment will be pull be VS code*/

        /*
        	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<types>
		<members>Account</members>
		<name>CustomObject</name>
	</types>
	<types>
		<members>*</members>
		<name>PermissionSet</name>
	</types>
	<types>
		<members>*</members>
		<name>Workflow</name>
	</types>
	<version>51.0</version>
</Package>*/
            }
}
